### ISSUE TITLE
Can I use this package for correcting batch effect using technical replicates?

### ISSUE THREAD

**Issue by yakshiUPR** [mikemc/metacal#9]
Hi, 

I came across your package through an issue (batch effect) that I was trying to solve with Benjamin Callahan (dada2) - https://github.com/benjjneb/dada2/issues/876 

 Benjamin suggested that I check metacal. I don't have mock communities but I did add technical replicates in the different sequencing runs. Based on the description of the package, I was left with the impression that I could use this package with the technical replicates, but from the tutorial, it is not clear. 

Can you please clarify if the technical replicates are useful for the usage of this package? 

Thanks

**Comment by mikemc** [comment]
Hi @yakshiUPR, thanks for your question. Our method can be used to quantify the ASV-specific bias between batches provided that technical replicates of the same community samples were sequenced across different batches. The tutorial does not cover this use case, but I can point you in the right direction or perhaps give some direct help if you are interested in doing this, as it would be a good use case for a new tutorial.

From skimming your thread in the DADA2 page, it sounds like our method might be useful in trying to understand and quantify the batch effects in your experiment, but I would start with trying to better understand any protocol differences (including bioinformatics choices) and determine the cause of the length variation between ASVs as just suggested by @benjjneb in https://github.com/benjjneb/dada2/issues/876#issuecomment-564607407. Both because this might solve the large batch effect and because a key step of applying our method to natural community samples is deciding how to match up taxa between batches, and for that it is very helpful to know if e.g. the ASVs in one batch have an extra couple bp on one end or the other.

There are currently two important limitations of our method to keep in mind:

1. Our method assumes that the bias associated with a particular taxon (here, ASV) and batch is consistent across samples within a batch. We have so far only tested this assumption for mock communities. It is a good default assumption, but is likely to be violated more often in natural community samples.

2. We have not yet developed a method for extrapolating the bias measured for the taxa in the technical replicates to other taxa that were not in the technical replicates. This means that our method cannot yet be used to calibrate the community-wide compositions of the samples that had no technical replicates; for those samples, you could only calibrate the relative abundances of the taxa that appeared in a technical replicate (and so their bias could be measured).

If you're still interested, I have a few questions: Just so I'm clear, by technical replicates you mean a natural community sample that was split into aliquots, one or more of which was measured in each batch (or in at least two batches)? How many aliquots per sample per batch? What environment or sample type are these (e.g., gut or soil) and did you homogenize the samples before aliquoting?

**Comment by yakshiUPR** [comment]
Hi @mikemc 

Thanks for answering! I think that the length issue might be causing some of the problem, but I do not think that it is causing the whole batch effect. As I responded to @benjjneb, I repeated the process using only the forward or reverse reads, and I made sure that all reads had the same length. After this, I still got the batch effect. Even though I resolve this issue through other methods, I would still like to learn how to manage the batch effect with the _metacal_, if you are up for it. 

I understand the limitations you state here. 

>...by technical replicates you mean a natural community sample that was split into aliquots, one or more of which was measured in each batch (or in at least two batches)? How many aliquots per sample per batch? What environment or sample type are these (e.g., gut or soil) and did you homogenize the samples before aliquoting?

The technical replicates are from natural soil communities (bulk and rhizosphere). After the 16S amplification, I split the PCR product into aliquots that were sequenced in at least two of the three MiSeq runs. The first two runs were sequenced without technical replicates among them. But, the third run has technical replicates of the other two runs (5 from the first run, and 9 from the second run). That third run has samples from an experiment that I am developing, so there we might encounter the second limitation you stated above, as not all samples will have the same microbial communities, but lets see. I did homogenized the amplicon prior to taking the aliquots. 

Let me know if this is ok, or if we need anything else. 

Thanks again!

Yakshi

**Comment by mikemc** [comment]
Ok! Reordering your reply a bit to share my thoughts:

> The technical replicates are from natural soil communities (bulk and rhizosphere). After the 16S amplification, I split the PCR product into aliquots that were sequenced in at least two of the three MiSeq runs. The first two runs were sequenced without technical replicates among them. But, the third run has technical replicates of the other two runs (5 from the first run, and 9 from the second run). That third run has samples from an experiment that I am developing, so there we might encounter the second limitation you stated above, as not all samples will have the same microbial communities, but lets see. I did homogenized the amplicon prior to taking the aliquots.

That makes sense. With this design, our method can be used to estimate the bias between run 1 and run 3 for the taxa in the 5 replicates, and between run 2 and run 3 for the taxa in the 9 replicates. We could then compare the bias for the taxa in both sets, to see if the bias between runs 1 and 3 and between runs 2 and 3 are similar. 

> I think that the length issue might be causing some of the problem, but I do not think that it is causing the whole batch effect. As I responded to @benjjneb, I repeated the process using only the forward or reverse reads, and I made sure that all reads had the same length. After this, I still got the batch effect. 

Ok, thanks for reminding me of that. In either of these configurations, do you see (at least some of) the exact same ASVs in the different runs? A simple way to check: if you have the ASV sequences (which you can get from the column names of the sequence table) stored as character vectors in objects called `seqs1`, `seqs2`, and `seqs3`, what is the output of
```r
# overlap between 1 and 2
length(intersect(seqs1, seqs2))
# overlap between 1 and 3
length(intersect(seqs1, seqs3))
# overlap between 2 and 3
length(intersect(seqs2, seqs3))
```

> I would still like to learn how to manage the batch effect with the _metacal_, if you are up for it.

"Managing the batch effect" might be a bit optimistic. But applying the (still limited) methods we've developed so far might help better understand the batch effect you are seeing, though it is hard for me to guess how useful it will be ahead of time. Your data and goals have some important differences from the datasets we've worked with so far, which means the easiest way for me to give step by step instructions would be for me to actually get my hands on your data. Are you willing to share the DADA2 results and sample information (enough so that I can link the replicates with each other) with me (privately is fine) and let me use them to develop some instructions that I can post here and on the metacal website?

**Comment by yakshiUPR** [comment]
Hi @mikemc, 

Yes, I would gladly share my data for this purpose. I prefer to do it by email, so I will be sending the data today to the email you have in your profile, unless you want me to send it to another address.

**Comment by mikemc** [comment]
Yes, please use the email in my profile, and I will take a look at it over the weekend.
